
package edu.depaul.ipd.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.0
 * Sun May 08 20:13:45 CDT 2011
 * Generated source version: 2.3.0
 */

@XmlRootElement(name = "getBootStyles", namespace = "http://ws.ipd.depaul.edu/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getBootStyles", namespace = "http://ws.ipd.depaul.edu/")

public class GetBootStyles {


}

