
package edu.depaul.ipd.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.0
 * Sun May 08 20:13:45 CDT 2011
 * Generated source version: 2.3.0
 */

@XmlRootElement(name = "getProductDetailResponse", namespace = "http://ws.ipd.depaul.edu/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getProductDetailResponse", namespace = "http://ws.ipd.depaul.edu/")

public class GetProductDetailResponse {

    @XmlElement(name = "return")
    private edu.depaul.ipd.ws.ProductDetail _return;

    public edu.depaul.ipd.ws.ProductDetail getReturn() {
        return this._return;
    }

    public void setReturn(edu.depaul.ipd.ws.ProductDetail new_return)  {
        this._return = new_return;
    }

}

